version: "3.8"
services:
  server:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:8"
    environment:
      MYSQL_ROOT_PASSWORD: "1432"
      MYSQL_DATABASE: "customer_db"
      MYSQL_USER: "sa"
      MYSQL_PASSWORD: "1432"


